In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'],
    "last": ["Schafer", 'Doe', 'Doe'],
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@gmail.com', 'JohnDoe@gmail.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [4]:
# Video 4 --> Basics of filtering data from dataframes and Series objects
# e.g. If we want to look up our survey data and only look at poople who know Python, we can filter that data out
# or maybe we only want to see results from a specific country, or people that have a specific salary range.
# we can do all that by filtering out data from our Series and df objects 
# Filtering --> the start of every project, separating data we do not want form data we do want

In [17]:
# basis for our filters, perform basic comparisons using our df --> get back interesting results
# Let's make a basic comparison and see what the result looks like,
# Let's say we want everyone who has the last name of Dou in our dataframe
df['last'] == 'Doe'
# what we get back is a Series object with boolean values

0    False
1     True
2     True
Name: last, dtype: bool

In [12]:
# Let's apply the above filter to our df
filt = (df['last'] == 'Doe') # now filt correspons to the filtered Series object we see above
df[filt] # pass filt (filtered Series object variable) directly to our df

# recall the word filter is a keyword and connot be used directly as a variable

  first last              email
1  Jane  Doe  JaneDoe@gmail.com
2  John  Doe  JohnDoe@gmail.com

In [16]:
df.loc[filt] # see that this line of code respresent the same as in df[filt]
# .l0c[...] --> used to search/gra especific rows and columns by label

  first last              email
1  Jane  Doe  JaneDoe@gmail.com
2  John  Doe  JohnDoe@gmail.com

In [15]:
df.loc[filt, 'email']
# first argument --> rows we want, second argument --> columns we want

1    JaneDoe@gmail.com
2    JohnDoe@gmail.com
Name: email, dtype: str

In [19]:
# 'and' and 'or' operators to filter data:
# & for and
# | for or

# get all of the rows where the last name is Doe and the first name is John:
filt = ((df['last'] == 'Doe') & (df['first'] == 'John'))
df.loc[filt]

  first last              email
2  John  Doe  JohnDoe@gmail.com

In [20]:
# get the email where the last name is Doe and the first name is John:
df.loc[filt, 'email']

2    JohnDoe@gmail.com
Name: email, dtype: str

In [24]:
# example using the or operator --> use the vertical var character |
# We want a filter where the last name is equal to Schafer or the first name is equal to John
filt = ((df['last'] == 'Schafer') | (df['first'] == 'John'))
df.loc[filt]
# PARENTHESIS MATTER!

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [27]:
# we can also get the opposite of a filter
# now, we would want all of the rows where the last name isn't Schafer and the first name isn't John
# --> filt = ((df['last'] != 'Schafer') & (df['first'] != 'John'))
# or we can also do (when defining the original before):
df[-filt]
df.loc[filt]

  first last              email
1  Jane  Doe  JaneDoe@gmail.com