In [1]:
import pandas as pd

In [2]:
people = {
    "first": ["Corey", 'Jane', 'John'],
    "last": ["Shafer", 'Doe', 'Doe'],
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@gmail.com', 'JohnDoe@gmail.com']
}

In [3]:
df = pd.DataFrame(people)
df

   first    last                    email
0  Corey  Shafer  CoreyMSchafer@gmail.com
1   Jane     Doe        JaneDoe@gmail.com
2   John     Doe        JohnDoe@gmail.com

In [5]:
# label --> identifier --> unique --> row
# Pandas does not enforce indexes being unique, but most of the time our index column will have unique values
# What might be a better index for our sample data above
df['email']
# maybe the amail address soul

0    CoreyMSchafer@gmail.com
1          JaneDoe@gmail.com
2          JohnDoe@gmail.com
Name: email, dtype: str

In [43]:
# what if we wanted to set these enail addresses as the index of our df?
df.set_index('email') # runs only once
# The email column now is far-left and bold (the original email column changes to the default index column)

KeyError: "None of ['email'] are in the columns"

In [41]:
# our dataframe didn't actually change, it still has the default index
df
# that is because pandas doen't do these type of changes uness we specify to do so

                         first    last
email
CoreyMSchafer@gmail.com  Corey  Shafer
JaneDoe@gmail.com         Jane     Doe
JohnDoe@gmail.com         John     Doe

In [44]:
# Let's say we actually want to set our index to the email column and have those changes carried over into future cells
df.set_index('email', inplace=True) # only runs once
# The upper line of code changes the index (row labels) of our pandas DataFrame to be the 'email' column.

KeyError: "None of ['email'] are in the columns"

In [27]:
# we now can see that the default dataframe has changes its default index for our email column set index:
df

                         first    last
email
CoreyMSchafer@gmail.com  Corey  Shafer
JaneDoe@gmail.com         Jane     Doe
JohnDoe@gmail.com         John     Doe

In [32]:
# We can check our df indexes by saying:
df.index # var df referenced to the .index attribute
# here, we have our indexes inside of a list besides the name of our index(as it was set to be the Series object slash column 'email') and their dtype

Index(['CoreyMSchafer@gmail.com', 'JaneDoe@gmail.com', 'JohnDoe@gmail.com'], dtype='str', name='email')

In [34]:
# why is this information and details about indexes useful?:
# --> The email address as the index gives us a nice unique identifier for our row
  # Remember that in the previous video we used .loc to search our dataframe by label,
  # therefore, these indexes that we set up are now the lables for the previous rows.
#so before used the default ranged index [0, 1, 2,..., n] but now we can find a specific
#row by passing in that label:

# df.loc[0] --> before, we were passing in a 0 as the label (row index)
# But now we can say:
df.loc['CoreyMSchafer@gmail.com']

first     Corey
last     Shafer
Name: CoreyMSchafer@gmail.com, dtype: str

In [38]:
df.loc['CoreyMSchafer@gmail.com', 'last'] # we can still pass in values for the specific columns as well

'Shafer'

In [45]:
# df.loc[0] --> No longer works since our set label(s) are now ur Series object slash column email data rather than the default integer ranged indexes [0, 1, 2,..., n]
# But if you want to use the default integer ranged index, we can still use iloc:
df.iloc[0]

first     Corey
last     Shafer
Name: CoreyMSchafer@gmail.com, dtype: str

In [47]:
# How to reset the index? --> Use the index reset method
df.reset_index(inplace=True) # argument 'inplace=True' passed in so that changes carry over
df

   index                    email  first    last
0      0  CoreyMSchafer@gmail.com  Corey  Shafer
1      1        JaneDoe@gmail.com   Jane     Doe
2      2        JohnDoe@gmail.com   John     Doe

In [ ]:
# Now, if you actually what you want the index to be when you're creating your DataFrame, then;
# you can simply set it there instead of setting it later using the .set_index() method.
# We can do this when we are loading in data from a CSV or other source as well