In [9]:
import pandas as pd

In [10]:
people = {
    "first": ['Corey', 'Jane', 'John', 'Adam'],
    "last": ['Schafer', 'Doe', 'Doe', 'Doe'],
    "email": ['CoreyMSchafer@gmail.com', 'JaneDoe@gmail.com', 'JohnDoe@gmail.com', 'A@email.com']
}

In [11]:
df = pd.DataFrame(people)
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com
3   Adam      Doe              A@email.com

In [12]:
# Sorting data
# Sort by last name (column 'last') --> use the .sort_values() method:
df.sort_values(by='last') # last name (column 'last') with values sorted alphabetically (ascending)

   first     last                    email
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com
3   Adam      Doe              A@email.com
0  Corey  Schafer  CoreyMSchafer@gmail.com

In [13]:
# If we wanted to sort these in descending orders, then we can pass-in an argument saying:
df.sort_values(by='last', ascending=False)

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com
3   Adam      Doe              A@email.com

In [14]:
# maybe you wanna sort on multiple columns --> pass-in a list for these columns.
# Let's say the first column we want to sort on is the 'last' in ascending order,
# and if there are duplicate last names, then we want to sort the 'first' after that.
df.sort_values(by=['last', 'first'], ascending=False)

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
2   John      Doe        JohnDoe@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
3   Adam      Doe              A@email.com

In [16]:
# Sort on multiple columns, but having one in descending order and another one in ascending order
df.sort_values(by=['last', 'first'], ascending=[False, True])
# 'last' in descending (False) and 'first' in ascending (True)

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
3   Adam      Doe              A@email.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [17]:
# save df and make sort permanent --> use inplace=True:
df.sort_values(by=['last', 'first'], ascending=[False, True], inplace=True)
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
3   Adam      Doe              A@email.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [18]:
# Set back to how it was before --> sorting the index with .sort_index() method:
df.sort_index()

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com
3   Adam      Doe              A@email.com

In [19]:
# wanting to sort a single column --> sort that single Series obj.
# We want to see sorted last names rather than an entire df sorted, then we can say:
df['last'].sort_values()

3        Doe
1        Doe
2        Doe
0    Schafer
Name: last, dtype: str