In [31]:
import pandas as pd

In [32]:
people = {
    "first": ['Corey', 'Jane', "John"],
    "last": ['Schafer', 'Doe', 'Doe'],
    "email": ['CoreyMSchafer@gmail.com', 'JaneDoe@gmail.com', 'JohnDoe@gmail.com'] 
}

In [39]:
df = pd.DataFrame(people)

In [40]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [41]:
# In this video we will be learning how to add and remove columns from our dataframes.
# WHile also take a look on how we can combine information from multiple columns into one.

# First, let's look at adding columns --> same thing as we did when we were updating values
# We can simply create a columns and pass in a Series of values that we want that column to have.

# First, let's say we want to combine our first name and last name columns into a single column.
df['first'] + ' ' + df['last']

0    Corey Schafer
1         Jane Doe
2         John Doe
dtype: str

In [42]:
# In order to add these values to a new column, we can simply say:
df['full_name'] = (df['first'] + ' ' + df['last']) # creating a new column called 'full_name' with the previous column addition
df

   first     last                    email      full_name
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@gmail.com       Jane Doe
2   John      Doe        JohnDoe@gmail.com       John Doe

In [43]:
# We could also create a new column using the .apply() method to have a new column for some mathematica analisis.
# We cannot use the dot notation when assigning a new column --> we have to use the brackets in order to make these assignments
# dot notation --> Python thinks you are trying to assign an attribute onto the dataframe object and not a column.

# Now let's look at removing columns
# let's say we don't want now our first and last name columns --> to remove these, we could use the .drop() method on our data frame;
df.drop(columns=['first', 'last'], inplace=True) # need the argument 'inplace=True' to update the original dataframe
df

                     email      full_name
0  CoreyMSchafer@gmail.com  Corey Schafer
1        JaneDoe@gmail.com       Jane Doe
2        JohnDoe@gmail.com       John Doe

In [44]:
# Now, if we want to remove the above's 'removing column' process, and split that full name column into two different coluns, we can use the string split method:
df['full_name'].str.split(' ') # the .split() method splits on spaces by default, so that here we are just reitering we want to split on a space, even thouh it is set as default
# the result of that split method is that we get the first name (first value) and the last name (second value) on a list.

0    [Corey, Schafer]
1         [Jane, Doe]
2         [John, Doe]
Name: full_name, dtype: object

In [45]:
# now, if we want to assign re gotten values from before's code, then we need to:
# --> expand the list, so that out values are actuallin in two different columns --> use the expand argument:
df['full_name'].str.split(' ', expand=True) # everthing that was in our split list, is now split up into columns

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [46]:
# Now what we need to do is to set two columns in our data frame to those two columns that were just returned in the previous code:
df[['first', 'last']] = (df['full_name'].str.split(' ', expand=True)) # to access multiple columns, within the brackets we can pass in a list so we're going to have two pairs of brackets
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@gmail.com       Jane Doe   Jane      Doe
2        JohnDoe@gmail.com       John Doe   John      Doe

In [59]:
# Let's now look at adding and removing rows of data

# There are different ways in which we might want to add rows to our dataframe
# First, we might just want to add a single row to our datafarme of new data
# Second, maybe we want to combine two dataframes together into a single datafame by appending the rows of one to another

# First, let's looks at adding a single row of data:
# df.append({'first': 'Tony'}, igonre_index=True) --> the .append() method not loner works in pandas, we have to use a different approach

new_row = (pd.DataFrame([{'first': 'Tony'}])) # passing a list with a dictionary (containing key and value)
df = pd.concat([df, new_row], ignore_index=True)
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@gmail.com       Jane Doe   Jane      Doe
2        JohnDoe@gmail.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN
4                      NaN            NaN   Tony      NaN
5                      NaN            NaN   Tony      NaN
6                      NaN            NaN   Tony      NaN

In [60]:
# To delete undesired new rows, we can use the .drop() method
df = df.drop(index=[4, 5, 6]) # remove indexes 4, 5, and 5 from our original dataframe df
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@gmail.com       Jane Doe   Jane      Doe
2        JohnDoe@gmail.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN

In [65]:
people = {
    "first": ['Tony', 'Steve'],
    "last": ['Stark', 'Rogers'],
    "email": ['Ironman@avenge.com', 'Cap@avenge.com']
}

df2 = pd.DataFrame(people)
df2

   first    last               email
0   Tony   Stark  Ironman@avenge.com
1  Steve  Rogers      Cap@avenge.com

In [82]:
# Let's say now we want to add the new dataframe df2 to our previous existing dataframe df:
# One way we could do this is, is to simply append the one dataframe to the other
# These have conflicting indexes and they also have columns that are not in the same order.
# Ignore the indexes when appending these so that they are assigned indexes properly

# df.append(df2, ignore_index=True) --> append df2 to our original dataframe / recall .append() not longer works for pandas past 2023

# what is the difference between concatenating and appending?

# Vertical concatenation (Stacking rows)
# --> To stack dataframes on top of each other, pass them as a list to .concat() method refernced to th pd module object.
# --> By default, it operates along with axis=0
df = pd.concat([df, df2], ignore_index=True) # sort=False by default
df

# why some methods have an in-place argument and others don't?
# RUN ONLY ONCE!!

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@gmail.com       Jane Doe   Jane      Doe
2        JohnDoe@gmail.com       John Doe   John      Doe
3       Ironman@avenge.com            NaN   Tony    Stark
4           Cap@avenge.com            NaN  Steve   Rogers

In [81]:
df = df.drop(index=[3, 4, 5])
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@gmail.com       Jane Doe   Jane      Doe
2        JohnDoe@gmail.com       John Doe   John      Doe

In [83]:
# Let's look at removing rows, let's remove Steve Rogers:
# We con do this in ALMOST the same way we would drop our columns, but
# instead of specifying the columns we are going to drop, we can simply pass in the indexes we want to drop:
df.drop(index=4) # here, we can set the in place argument to true (inplace=True)

# What is the difference between passing only an integer and a list for the argument of .drop() setting with index=(int)

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@gmail.com       Jane Doe   Jane      Doe
2        JohnDoe@gmail.com       John Doe   John      Doe
3       Ironman@avenge.com            NaN   Tony    Stark

In [84]:
# More complicated --> dropping rows using a conditional 
# We can prob be using .loc[] but we can also do it using .drop()

# So, if we wanted to drop all of the rows where the last name is equal to Doe, so
# we have two of those values here, then we can pass-in the index of that filter

# pass-in the conditional '[df['last'] == 'Doe']' inside of our brackets
df.drop(index=df[df['last'] == 'Doe'].index) # we want the indexes since we're saying index is equal to... thewn we use .index
# It removes those value/rows with the last name of DOE

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
3       Ironman@avenge.com            NaN   Tony    Stark
4           Cap@avenge.com            NaN  Steve   Rogers

In [88]:
# The previous code is kind of hard to read so we would pull the conditional out into its own variable,
# and instead, we would say something like this:
filt = (df['last'] == 'Doe')
df.drop(index=df[filt].index)

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
3       Ironman@avenge.com            NaN   Tony    Stark
4           Cap@avenge.com            NaN  Steve   Rogers