In [31]:
import pandas as pd

In [32]:
people = {
    "first": ['Corey', 'Jane', "John"],
    "last": ['Schafer', 'Doe', 'Doe'],
    "email": ['CoreyMSchafer@gmail.com', 'JaneDoe@gmail.com', 'JohnDoe@gmail.com'] 
}

In [39]:
df = pd.DataFrame(people)

In [40]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [41]:
# In this video we will be learning how to add and remove columns from our dataframes.
# WHile also take a look on how we can combine information from multiple columns into one.

# First, let's look at adding columns --> same thing as we did when we were updating values
# We can simply create a columns and pass in a Series of values that we want that column to have.

# First, let's say we want to combine our first name and last name columns into a single column.
df['first'] + ' ' + df['last']

0    Corey Schafer
1         Jane Doe
2         John Doe
dtype: str

In [42]:
# In order to add these values to a new column, we can simply say:
df['full_name'] = (df['first'] + ' ' + df['last']) # creating a new column called 'full_name' with the previous column addition
df

   first     last                    email      full_name
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@gmail.com       Jane Doe
2   John      Doe        JohnDoe@gmail.com       John Doe

In [43]:
# We could also create a new column using the .apply() method to have a new column for some mathematica analisis.
# We cannot use the dot notation when assigning a new column --> we have to use the brackets in order to make these assignments
# dot notation --> Python thinks you are trying to assign an attribute onto the dataframe object and not a column.

# Now let's look at removing columns
# let's say we don't want now our first and last name columns --> to remove these, we could use the .drop() method on our data frame;
df.drop(columns=['first', 'last'], inplace=True) # need the argument 'inplace=True' to update the original dataframe
df

                     email      full_name
0  CoreyMSchafer@gmail.com  Corey Schafer
1        JaneDoe@gmail.com       Jane Doe
2        JohnDoe@gmail.com       John Doe

In [44]:
# Now, if we want to remove the above's 'removing column' process, and split that full name column into two different coluns, we can use the string split method:
df['full_name'].str.split(' ') # the .split() method splits on spaces by default, so that here we are just reitering we want to split on a space, even thouh it is set as default
# the result of that split method is that we get the first name (first value) and the last name (second value) on a list.

0    [Corey, Schafer]
1         [Jane, Doe]
2         [John, Doe]
Name: full_name, dtype: object

In [45]:
# now, if we want to assign re gotten values from before's code, then we need to:
# --> expand the list, so that out values are actuallin in two different columns --> use the expand argument:
df['full_name'].str.split(' ', expand=True) # everthing that was in our split list, is now split up into columns

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [46]:
# Now what we need to do is to set two columns in our data frame to those two columns that were just returned in the previous code:
df[['first', 'last']] = (df['full_name'].str.split(' ', expand=True)) # to access multiple columns, within the brackets we can pass in a list so we're going to have two pairs of brackets
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@gmail.com       Jane Doe   Jane      Doe
2        JohnDoe@gmail.com       John Doe   John      Doe

In [55]:
# Let's now look at adding and removing rows of data

# There are different ways in which we might want to add rows to our dataframe
# First, we might just want to add a single row to our datafarme of new data
# Second, maybe we want to combine two dataframes together into a single datafame by appending the rows of one to another

# First, let's looks at adding a single row of data:
new_row = (pd.DataFrame([{'first': 'Tony'}])) # passing a list with a dictionary (containing key and value)
df = pd.concat([df, new_row], ignore_index=True)
df

# To delete undesired new rows, we can use the .drop() method

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@gmail.com       Jane Doe   Jane      Doe
2        JohnDoe@gmail.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN
4                      NaN            NaN   Tony      NaN
5                      NaN            NaN   Tony      NaN